/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.TicTacToe.Campaign.Campaign;
import com.TicTacToe.Caro.Play2PlayersCaro;
import com.TicTacToe.Caro.PlayWithAiCaro;
import com.TicTacToe.Connect4.Play2PlayersConnect4;
import com.TicTacToe.Connect4.PlayWithAiConnect4;
import com.TicTacToe.TicTacToe.JFrameMain;
import static com.TicTacToe.TicTacToe.JFrameMain.jFrame;
import com.TicTacToe.TicTacToe.Play2Players;
import com.TicTacToe.TicTacToe.PlayWithAI;
import com.TicTacToe.TicTacToe.PlayWithAI.Bot;
import java.awt.AlphaComposite;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author tuyen
 */
public class CaroForm extends javax.swing.JFrame {

    private Container JPanelMain;

    /**
     * Creates new form CaroForm
     */
    private boolean isPlaying = true; // ban đầu đang phát nhạc

    public CaroForm() {

        initComponents();

        JFrameMain.jFrame = this;
        ImageIcon gifIcon = new ImageIcon(getClass().getResource("/RES/fox.gif"));
        anhdong.setIcon(gifIcon);
        anhdong.setBounds(560, 340, gifIcon.getIconWidth(), gifIcon.getIconHeight());
        playBackgroundMusic("/RES/phonk.wav");

        ImageIcon gifIcon1 = new ImageIcon(getClass().getResource("/RES/wasp.gif"));
        anhdong1.setIcon(gifIcon1);
        anhdong1.setBounds(560, 340, gifIcon1.getIconWidth(), gifIcon1.getIconHeight());

        jSpinnerdorongbang.setModel(new SpinnerNumberModel(5, 5, 20, 1));
        jSpinnerdorongbang.setEnabled(false);
    }

    private Clip clip;

// Hàm này dùng để load và phát nhạc nền
    private void playBackgroundMusic(String path) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource(path));
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.loop(Clip.LOOP_CONTINUOUSLY); // phát lặp lại liên tục
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnplaywithAI = new java.awt.Button();
        btnexit = new java.awt.Button();
        btnplaywithplayer = new java.awt.Button();
        btnchampaign = new java.awt.Button();
        btnHighScore = new java.awt.Button();
        nguoichoi2 = new javax.swing.JLabel();
        nguoichoi1 = new javax.swing.JLabel();
        player1 = new java.awt.TextField();
        player2 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcombobanco = new javax.swing.JComboBox<>();
        jSpinnerdorongbang = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        anhdong = new javax.swing.JLabel();
        anhdong1 = new javax.swing.JLabel();
        offclip = new javax.swing.JButton();
        anhnen = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GAME CARO");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnplaywithAI.setActionCommand("Exit");
        btnplaywithAI.setBackground(new java.awt.Color(255, 153, 51));
        btnplaywithAI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnplaywithAI.setForeground(new java.awt.Color(255, 255, 255));
        btnplaywithAI.setLabel("MODE AI");
        btnplaywithAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaywithAIActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaywithAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 200, 40));

        btnexit.setActionCommand("Exit");
        btnexit.setBackground(new java.awt.Color(255, 153, 51));
        btnexit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setLabel("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 200, 40));

        btnplaywithplayer.setActionCommand("Exit");
        btnplaywithplayer.setBackground(new java.awt.Color(255, 153, 51));
        btnplaywithplayer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnplaywithplayer.setForeground(new java.awt.Color(255, 255, 255));
        btnplaywithplayer.setLabel("MODE PLAYER\n");
        btnplaywithplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaywithplayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaywithplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 200, 40));

        btnchampaign.setActionCommand("Exit");
        btnchampaign.setBackground(new java.awt.Color(255, 153, 51));
        btnchampaign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnchampaign.setForeground(new java.awt.Color(255, 255, 255));
        btnchampaign.setLabel("CAMPAIGN");
        btnchampaign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchampaignActionPerformed(evt);
            }
        });
        getContentPane().add(btnchampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 200, 40));

        btnHighScore.setActionCommand("Exit");
        btnHighScore.setBackground(new java.awt.Color(255, 153, 51));
        btnHighScore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHighScore.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHighScore.setForeground(new java.awt.Color(255, 255, 255));
        btnHighScore.setLabel("HIGH SCORE");
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnHighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 200, 40));

        nguoichoi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nguoichoi2.setForeground(new java.awt.Color(255, 255, 255));
        nguoichoi2.setText("Tên người chơi 2:");
        getContentPane().add(nguoichoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 30));

        nguoichoi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nguoichoi1.setForeground(new java.awt.Color(255, 255, 255));
        nguoichoi1.setText("Tên người chơi 1:");
        getContentPane().add(nguoichoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 30));

        player1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        player1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 190, 30));

        player2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        player2.setForeground(new java.awt.Color(204, 204, 204));
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chế độ game :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Độ rộng bảng :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jcombobanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARO (3x3)", "CARO (4x4)", "CARO (5x5)+", " " }));
        jcombobanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobancoActionPerformed(evt);
            }
        });
        getContentPane().add(jcombobanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 180, 30));
        getContentPane().add(jSpinnerdorongbang, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 180, 30));

        jLabel3.setFont(new java.awt.Font("STXingkai", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("CARO GAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 320, 90));

        anhdong.setText("...");
        anhdong.setToolTipText("");
        anhdong.setMaximumSize(new java.awt.Dimension(30, 30));
        anhdong.setMinimumSize(new java.awt.Dimension(30, 30));
        getContentPane().add(anhdong, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, -1));

        anhdong1.setToolTipText("");
        getContentPane().add(anhdong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        offclip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/icvolume.jpg"))); // NOI18N
        offclip.setText("jButton1");
        offclip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offclipActionPerformed(evt);
            }
        });
        getContentPane().add(offclip, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 100, 30));

        anhnen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        anhnen.setForeground(new java.awt.Color(255, 255, 255));
        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/gamecaro.jpg"))); // NOI18N
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1150, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcombobancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobancoActionPerformed
        String selected = (String) jcombobanco.getSelectedItem();
        if (selected.equals("CARO (5x5)+")) {
            jSpinnerdorongbang.setEnabled(true);
        } else {
            jSpinnerdorongbang.setEnabled(false);
        }
    }//GEN-LAST:event_jcombobancoActionPerformed

    private void btnplaywithAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaywithAIActionPerformed
        String playerName = player2.getText().trim();
        if (playerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi 1!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Set board size
        int boardSize = getBoardSize();
        if (boardSize >= 5) { // Caro
            PlayWithAiCaro.GameBot = PlayWithAI.Bot.HEURISTIC_BOT;
            PlayWithAiCaro.newRow = boardSize;
            new PlayWithAiCaro(playerName);
        } else if (boardSize == 3) { // Tic Tac Toe
            PlayWithAI.GameBot = PlayWithAI.Bot.HEURISTIC_BOT;
            PlayWithAI.newRow = boardSize;
            new PlayWithAI(playerName);
        } else if (boardSize == 4) { // Connect 4
            PlayWithAiConnect4.GameBot = PlayWithAI.Bot.HEURISTIC_BOT;
            PlayWithAiConnect4.newRow = boardSize;
            new PlayWithAiConnect4(playerName);
        }
        setVisible(false);

    }//GEN-LAST:event_btnplaywithAIActionPerformed

    private void btnplaywithplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaywithplayerActionPerformed
        String player1Name = player2.getText().trim();
        String player2Name = player1.getText().trim();
        if (player1Name.isEmpty() || player2Name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên cả hai người chơi!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Set board size
        int boardSize = getBoardSize();
        if (boardSize >= 5) { // Caro
                Play2PlayersCaro.newRow = boardSize;
                new Play2PlayersCaro(player1Name, player2Name);
            } else if (boardSize == 3) { // Tic Tac Toe
                Play2Players.newRow = boardSize;
                new Play2Players(player1Name, player2Name);
            } else if (boardSize == 4) { // Connect 4
                Play2PlayersConnect4.newRow = boardSize;
                new Play2PlayersConnect4(player1Name, player2Name);
            }
        setVisible(false);


    }//GEN-LAST:event_btnplaywithplayerActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        if (clip != null) {
            clip.stop();
            clip.close();
        }
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2ActionPerformed

    private void btnchampaignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchampaignActionPerformed
        // TODO add your handling code here:
        String name = player2.getText();
        if (name.isEmpty() || name.equals("Player 1")) {
            JOptionPane.showMessageDialog(null, "Please enter your name!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jFrame.setVisible(false);
        Campaign campaign = new Campaign(name);
        campaign.PlayCamp1();
    }//GEN-LAST:event_btnchampaignActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        // TODO add your handling code here:
        HighScoreForm highScore = new HighScoreForm();
            highScore.CreateAndShow();
            jFrame.setVisible(false);
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void offclipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offclipActionPerformed
        // TODO add your handling code here:
        if (clip == null) {
            return;
        }

        if (isPlaying) {
            clip.stop();
            isPlaying = false;
            offclip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/icmute.png"))); 
        } else {
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start();
            isPlaying = true;
            offclip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/icvolume.jpg"))); // icon có tiếng
        }
    }//GEN-LAST:event_offclipActionPerformed

    private int getBoardSize() {
        String selected = (String) jcombobanco.getSelectedItem();
        if (selected.equals("CARO (3x3)")) {
            return 3;
        } else if (selected.equals("CARO (4x4)")) {
            return 4;
        } else {
            return (Integer) jSpinnerdorongbang.getValue();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhdong;
    private javax.swing.JLabel anhdong1;
    private javax.swing.JLabel anhnen;
    private java.awt.Button btnHighScore;
    private java.awt.Button btnchampaign;
    private java.awt.Button btnexit;
    private java.awt.Button btnplaywithAI;
    private java.awt.Button btnplaywithplayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinnerdorongbang;
    private javax.swing.JComboBox<String> jcombobanco;
    private javax.swing.JLabel nguoichoi1;
    private javax.swing.JLabel nguoichoi2;
    private javax.swing.JButton offclip;
    private java.awt.TextField player1;
    private java.awt.TextField player2;
    // End of variables declaration//GEN-END:variables
}
